spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_dev
    username: erp_user
    password: erp_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA Configuration for Development
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

  # Mail Configuration (for development)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

# Development specific logging
logging:
  level:
    com.company.erp: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/erp-dev.log

# Security Configuration for Development
app:
  jwt:
    secret: devSecretKey123456789012345678901234567890123456789012345678901234567890
    expiration: 86400000 # 24 hours in development

  security:
    cors:
      enabled: true
      allowed-origins:
        - http://localhost:3000
        - http://localhost:5173
        - http://127.0.0.1:3000
        - http://127.0.0.1:5173
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# Actuator for Development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always