spring:
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/erp_prod}
    username: ${DATABASE_USERNAME:erp_user}
    password: ${DATABASE_PASSWORD:your_secure_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  # JPA Configuration for Production
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@company.com}
    password: ${MAIL_PASSWORD:your-secure-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Production Logging
logging:
  level:
    com.company.erp: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: INFO
  file:
    name: /var/log/erp/erp-prod.log
    max-size: 100MB
    max-history: 30

# Security Configuration for Production
app:
  jwt:
    secret: ${JWT_SECRET:your_very_secure_secret_key_here_minimum_64_characters_long}
    expiration: 28800000 # 8 hours in production

  security:
    cors:
      enabled: true
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://erp.yourcompany.com}
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  # File Storage Configuration
  file:
    upload-dir: ${FILE_UPLOAD_DIR:/opt/erp/uploads}
    max-file-size: 10MB

# Actuator for Production (Restricted)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
  http2:
    enabled: true
  forward-headers-strategy: native